# Generated by Django 5.0.4 on 2026-03-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('funeral_type', models.CharField(choices=[('new', 'Новая могила'), ('relative', 'Подзахоронение'), ('cremation', 'Кремация')], max_length=20, verbose_name='Тип услуги')),
                ('selected_services', models.JSONField(default=list, verbose_name='Выбранные услуги (ID)')),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма (ориентир)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('meeting', 'Встреча назначена'), ('closed', 'Завершена')], default='new', max_length=20)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
