# Generated by Django 5.0.4 on 2026-04-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_lead_request_type_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='autopsy_type',
            field=models.CharField(blank=True, choices=[('paid', 'Платное вскрытие (1-2 дня)'), ('free', 'Бесплатное вскрытие (2-3 дня)')], default='paid', max_length=10, null=True, verbose_name='Вскрытие'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='funeral_type',
            field=models.CharField(blank=True, choices=[('new', 'Новая могила'), ('relative', 'Подзахоронение'), ('cremation', 'Кремация')], max_length=20, null=True, verbose_name='Тип услуги'),
        ),
    ]
