# Generated by Django 5.0.4 on 2026-03-16 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('service_type', models.CharField(choices=[('funeral', 'Ритуальные услуги (Захоронение)'), ('cremation', 'Кремация'), ('common', 'Общее (для всех)')], default='common', max_length=20)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Обязательно')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('applicability', models.CharField(choices=[('all', 'Для всех'), ('new', 'Только новая могила'), ('relative', 'Только подзахоронение'), ('cremation', 'Только кремация')], default='all', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
