# Generated by Django 5.0.4 on 2026-03-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_is_active_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='selection_type',
            field=models.CharField(choices=[('single', 'Одиночный выбор (radio)'), ('multiple', 'Множественный выбор (checkbox)')], default='multiple', max_length=10),
        ),
    ]
