# Generated by Django 5.0.4 on 2026-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='autopsy_type',
            field=models.CharField(choices=[('paid', 'Платное вскрытие (1-2 дня)'), ('free', 'Бесплатное вскрытие (2-3 дня)')], default='paid', max_length=10, verbose_name='Вскрытие'),
        ),
    ]
