# Generated by Django 5.0.4 on 2026-04-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_lead_autopsy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='request_type',
            field=models.CharField(choices=[('funeral', 'Организация похорон'), ('consultation', 'Консультация'), ('callback', 'Обратный звонок')], default='funeral', max_length=20, verbose_name='Тип обращения'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('calculator', 'Калькулятор услуг'), ('callback', 'Обратный звонок'), ('contacts', 'Страница контактов')], default='calculator', max_length=20, verbose_name='Источник заявки'),
        ),
    ]
