# Generated by Django 5.0.4 on 2026-03-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='applicability',
            field=models.CharField(choices=[('all', 'Для всех'), ('funeral', 'Захоронение (новая + подзахоронение)'), ('cremation', 'Только кремация')], default='all', max_length=20),
        ),
    ]
